name: DevCard

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard_horizontal
        uses: dailydotdev/action-devcard@3.2.0
        with:
          user_id: ${{ secrets.USER_ID }}
          commit_message: "Update ${filename}"
          type: "wide"
          commit_filename: "devcard_horizontal.png"
      - name: devcard_vertical
        uses: dailydotdev/action-devcard@3.2.0
        with:
          user_id: ${{ secrets.USER_ID }}
          commit_message: "Update ${filename}"
          commit_filename: "devcard_vertical.png"
